[package]
name = "cringegen-xyplot"
version = "0.1.0"
edition = "2021"
authors = ["CringeGen contributors"]
description = "XY Plot support for CringeGen"

[dependencies]
imx = "0.1.17"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
anyhow = "1.0.97"
